# nixpacks.toml

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run start"

[environment]
NODE_ENV = "production"
PORT = 5000

[build]
publishDir = "frontend/build"
